# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_delete_2(object):
    def setupUi(self, delete_2):
        delete_2.setObjectName("delete_2")
        delete_2.resize(886, 836)
        self.formLayout = QtWidgets.QFormLayout(delete_2)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(delete_2)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.label_2 = QtWidgets.QLabel(delete_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(delete_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.line = QtWidgets.QFrame(delete_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.line)
        self.label_3 = QtWidgets.QLabel(delete_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.name = QtWidgets.QLabel(delete_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name.setFont(font)
        self.name.setText("")
        self.name.setObjectName("name")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.name)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.label_4 = QtWidgets.QLabel(delete_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.ph_no = QtWidgets.QLabel(delete_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ph_no.setFont(font)
        self.ph_no.setText("")
        self.ph_no.setObjectName("ph_no")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.ph_no)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        self.label_5 = QtWidgets.QLabel(delete_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.e_mail = QtWidgets.QLabel(delete_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.e_mail.setFont(font)
        self.e_mail.setText("")
        self.e_mail.setObjectName("e_mail")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.e_mail)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(11, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout.setLayout(13, QtWidgets.QFormLayout.FieldRole, self.verticalLayout)
        self.search = QtWidgets.QPushButton(delete_2)
        self.search.setObjectName("search")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.search)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(12, QtWidgets.QFormLayout.FieldRole, spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(15, QtWidgets.QFormLayout.FieldRole, spacerItem6)
        self.clear = QtWidgets.QPushButton(delete_2)
        self.clear.setObjectName("clear")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.clear)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(19, QtWidgets.QFormLayout.FieldRole, spacerItem7)
        self.cancel = QtWidgets.QPushButton(delete_2)
        self.cancel.setObjectName("cancel")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.FieldRole, self.cancel)
        self.delButton = QtWidgets.QPushButton(delete_2)
        self.delButton.setObjectName("delButton")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.delButton)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(17, QtWidgets.QFormLayout.FieldRole, spacerItem8)
        self.label_6 = QtWidgets.QLabel(delete_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.search.clicked.connect(self.searchdb)
        self.delButton.setEnabled(False)
        self.clear.clicked.connect(self.cleartxt)
        self.cancel.clicked.connect(delete_2.close)
        self.delButton.clicked.connect(self.delete)
        self.retranslateUi(delete_2)
        QtCore.QMetaObject.connectSlotsByName(delete_2)

    def retranslateUi(self, delete_2):
        _translate = QtCore.QCoreApplication.translate
        delete_2.setWindowTitle(_translate("delete_2", "Delete"))
        self.label.setText(_translate("delete_2", "Delete"))
        self.label_2.setText(_translate("delete_2", "Registration Number"))
        self.label_3.setText(_translate("delete_2", "Name"))
        self.label_4.setText(_translate("delete_2", "Phone Number"))
        self.label_5.setText(_translate("delete_2", "E-Mail"))
        self.search.setText(_translate("delete_2", "Search"))
        self.clear.setText(_translate("delete_2", "Clear"))
        self.cancel.setText(_translate("delete_2", "Cancel"))
        self.delButton.setText(_translate("delete_2", "Delete"))
    def searchdb(self):
        import db
        a=db.searchStudent(self.lineEdit.text())
        self.delButton.setEnabled(True)
        self.name.setText(a[0])
        self.ph_no.setText(a[1])
        self.e_mail.setText(a[2])
        self.label_6.setText("Are you sure?")
    def delete(self):
        import db
        db.deleteStudent(self.lineEdit.text())
        self.label_6.setText("Deleted")
    def cleartxt(self):
      self.name.clear()
      self.lineEdit.clear()
      self.ph_no.clear()
      self.e_mail.clear()
      self.delButton.setEnabled(False)
      self.label_6.clear()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    delete_2 = QtWidgets.QWidget()
    ui = Ui_delete_2()
    ui.setupUi(delete_2)
    delete_2.show()
    sys.exit(app.exec_())

