# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modify.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_modify(object):
    def setupUi(self, modify):
        modify.setObjectName("modify")
        modify.resize(886, 836)
        self.formLayout = QtWidgets.QFormLayout(modify)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(modify)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.label_2 = QtWidgets.QLabel(modify)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(modify)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.line = QtWidgets.QFrame(modify)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.line)
        self.label_3 = QtWidgets.QLabel(modify)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.label_4 = QtWidgets.QLabel(modify)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        self.label_5 = QtWidgets.QLabel(modify)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(11, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout.setLayout(13, QtWidgets.QFormLayout.FieldRole, self.verticalLayout)
        self.search = QtWidgets.QPushButton(modify)
        self.search.setObjectName("search")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.search)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(12, QtWidgets.QFormLayout.FieldRole, spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(17, QtWidgets.QFormLayout.FieldRole, spacerItem6)
        self.clear = QtWidgets.QPushButton(modify)
        self.clear.setObjectName("clear")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.clear)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(19, QtWidgets.QFormLayout.FieldRole, spacerItem7)
        self.cancel = QtWidgets.QPushButton(modify)
        self.cancel.setObjectName("cancel")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.FieldRole, self.cancel)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(15, QtWidgets.QFormLayout.FieldRole, spacerItem8)
        self.pushButton = QtWidgets.QPushButton(modify)
        self.pushButton.setEnabled(False)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.name = QtWidgets.QLineEdit(modify)
        self.name.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.name)
        self.ph_no = QtWidgets.QLineEdit(modify)
        self.ph_no.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ph_no.setFont(font)
        self.ph_no.setObjectName("ph_no")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.ph_no)
        self.e_mail = QtWidgets.QLineEdit(modify)
        self.e_mail.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.e_mail.setFont(font)
        self.e_mail.setObjectName("e_mail")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.e_mail)
        self.search.clicked.connect(self.searchdb)
        self.clear.clicked.connect(self.cleartxt)
        self.pushButton.clicked.connect(self.modify)
        self.cancel.clicked.connect(modify.close)        
        self.retranslateUi(modify)
        QtCore.QMetaObject.connectSlotsByName(modify)

    def retranslateUi(self, modify):
        _translate = QtCore.QCoreApplication.translate
        modify.setWindowTitle(_translate("modify", "Modify"))
        self.label.setText(_translate("modify", "Modify"))
        self.label_2.setText(_translate("modify", "Registration Number"))
        self.label_3.setText(_translate("modify", "Name"))
        self.label_4.setText(_translate("modify", "Phone Number"))
        self.label_5.setText(_translate("modify", "E-Mail"))
        self.search.setText(_translate("modify", "Search"))
        self.clear.setText(_translate("modify", "Clear"))
        self.cancel.setText(_translate("modify", "Cancel"))
        self.pushButton.setText(_translate("modify", "Modify"))

    def searchdb(self):
        import db
        a=db.searchStudent(self.lineEdit.text())
        self.name.setText(a[0])
        self.ph_no.setText(a[1])
        self.e_mail.setText(a[2])
        self.name.setEnabled(True)
        self.ph_no.setEnabled(True)
        self.e_mail.setEnabled(True)
        self.pushButton.setEnabled(True)
        self.lineEdit.setEnabled(False)
    def cleartxt(self):
      self.name.clear()
      self.lineEdit.clear()
      self.ph_no.clear()
      self.e_mail.clear()
      self.lineEdit.setEnabled(True)
      self.pushButton.setEnabled(False)
      self.pushButton.setText("Modify")
    def modify(self):
      import db
      a=[]
      a.append(self.name.text())
      a.append(self.lineEdit.text())
      a.append(self.ph_no.text())
      a.append(self.e_mail.text())
      db.modifyStudent((self.lineEdit.text()),a)
      self.pushButton.setText("Successfully Modified")        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    modify = QtWidgets.QWidget()
    ui = Ui_modify()
    ui.setupUi(modify)
    modify.show()
    sys.exit(app.exec_())

